import streamlit as st
import numpy as np
import matplotlib.pyplot as plt

st.set_page_config(page_title="Toy 2 — Coupled Closed Loops", layout="wide")
st.title("Toy 2 — Coupled System (Exact Closed Loops)")
st.caption("Exact conservative rotation (no numerical energy injection) + optional shear view.")

# -------------------------
# Helpers
# -------------------------
def plot_phase(Z, S, title):
    fig, ax = plt.subplots(figsize=(6, 6))
    ax.plot(Z, S, linewidth=1.1)
    ax.set_xlabel("Z (trap strength)")
    ax.set_ylabel("Σ (entropy escape)")
    ax.set_title(title)
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.grid(True, alpha=0.35)
    ax.set_aspect("equal", adjustable="box")
    st.pyplot(fig)
    plt.close(fig)

def plot_timeseries(Z, S):
    fig, ax = plt.subplots(figsize=(8, 3))
    ax.plot(Z, label="Z")
    ax.plot(S, label="Σ")
    ax.set_xlabel("step")
    ax.set_ylabel("value")
    ax.set_title("Time Series (Conservative Loop)")
    ax.legend()
    ax.grid(True, alpha=0.35)
    st.pyplot(fig)
    plt.close(fig)

# -------------------------
# Model (Toy 2)
# -------------------------
def toy2_closed_loops(
    steps: int,
    theta: float,
    amp: float,
    shear: float,
    centre=(0.5, 0.5),
):
    """
    Conservative closed loop using an exact rotation matrix in (u,v) about centre.
    Then apply an optional shear for display only (keeps bounded and stable).
    """
    cx, cy = centre
    u, v = amp, -0.6 * amp  # initial offset

    Z = np.empty(steps)
    S = np.empty(steps)

    c = np.cos(theta)
    s = np.sin(theta)

    for i in range(steps):
        # exact rotation (energy-preserving)
        u, v = (c * u - s * v), (s * u + c * v)

        # map back to (Z, Σ)
        z = cx + u
        sig = cy + v

        # optional shear "view" (tilts geometry without changing loop energy)
        # shear transforms: [z']   [1  shear][z-cx] + centre
        #                   [s'] = [0   1  ][s-cy]
        if shear != 0.0:
            dz = z - cx
            ds = sig - cy
            z = cx + dz + shear * ds
            sig = cy + ds

        # keep within [0,1] by mild clipping (should not be necessary if amp small)
        z = float(np.clip(z, 0.0, 1.0))
        sig = float(np.clip(sig, 0.0, 1.0))

        Z[i] = z
        S[i] = sig

    return Z, S

# -------------------------
# UI
# -------------------------
with st.sidebar:
    st.header("Controls")
    steps = st.slider("Steps", 500, 30000, 5000, 500)
    theta = st.slider("Rotation per step (θ)", 0.001, 0.25, 0.03, 0.001)
    amp = st.slider("Amplitude", 0.01, 0.49, 0.18, 0.01)
    shear = st.slider("Shear (view tilt)", -1.50, 1.50, 0.60, 0.05)
    show_ts = st.checkbox("Show time series", True)

Z, S = toy2_closed_loops(steps, theta, amp, shear)

plot_phase(Z, S, "Phase Space: Exact Closed Loop (Sheared View)")
if show_ts:
    plot_timeseries(Z, S)

st.markdown(
    """
**Why this fixes your Toy 2**
- The loop is generated by an **exact rotation matrix**, so it can’t “blow up” to ±1e6.
- The “tilt/break” look comes from the **shear view**, not from unstable integration.
"""
)